NAME = 		ex03

SRCS = 		main.cpp \
			HumanB.cpp \
			HumanA.cpp \
			Weapon.cpp \

OBJS = 		${SRCS:.cpp=.o}

CPP	= 		c++

CPPFLAGS = 	-Wall -Werror -Wextra -std=c++98

HEADER = 	Weapon.hpp HumanB.hpp HumanA.hpp \

all:		$(NAME)

.o: 		$(SRCS) $(HEADER)
			$(CPP) $(CPPFLAGS) -c $< -o $@

$(NAME):	$(OBJS)
			$(CPP) $(CPPFLAGS) $(OBJS) -o $(NAME)

clean:
			@rm -rf $(OBJS)

fclean:		clean
			@rm -rf $(NAME)

re:			fclean all

.PHONY:		all clean fclean re